import Cabecalho from "@/components/Cabecalho/Cabecalho";
import Rodape from "@/components/Rodape/Rodape";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Exemplo Rotas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Cabecalho/>
          {children}
        <Rodape/>
      </body>
    </html>
  );
}
